/**
 * authority.js — server-authoritative RNG + receipts (CommonJS).
 *
 * Why this exists: any JS shipped to the browser can be read/patched via F12
 * (Math.random, Casino.tokens += N, ...). The only real fix is to roll the
 * outcome on the server (node) and hand the client a signed receipt.
 *
 * - Works when playing via `node server.js` (same-origin /api/*).
 * - On itch.io static hosting there is no server, so the client falls back
 *   to local RNG (and remains cheatable there — this is stated openly).
 *
 * Zero dependencies — only node:crypto.
 */
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

// --- Canonical price catalog (generated by scripts/build-protect.mjs) --------
let CATALOG = null;
function loadCatalog() {
    if (CATALOG) return CATALOG;
    try {
        const p = path.join(__dirname, 'catalog.json');
        CATALOG = JSON.parse(fs.readFileSync(p, 'utf8'));
    } catch (e) {
        // Dev fallback when build-protect hasn't run yet: permissive but capped.
        CATALOG = { weapons: {}, rods: {}, fishValues: {}, fishValueMult: 1, tokenPrice: 100, cashoutRate: 70, maxSellPerFish: 100000, ammoPrices: {}, ammoMax: {} };
    }
    return CATALOG;
}

// Shop rate limiting: 20 econ ops / min per IP (humans click slower).
const econHits = new Map();
function econLimited(ip) {
    const now = Date.now();
    let arr = econHits.get(ip) || [];
    arr = arr.filter(t => now - t < 60000);
    arr.push(now);
    econHits.set(ip, arr);
    return arr.length > 20;
}

// Secret for HMAC receipts. Set AH_SECRET in env for stable receipts across
// restarts; otherwise a random per-boot secret is used (receipts then only
// verify within the same boot — fine for gameplay, saves stay local).
const SECRET = process.env.AH_SECRET || ('boot-' + crypto.randomBytes(16).toString('hex'));

// --- Rate limiting: 30 casino rolls / min per IP (generous for humans) ------
const hits = new Map(); // ip -> [timestamps]
const WINDOW_MS = 60_000;
const MAX_HITS = 30;
function rateLimited(ip) {
    const now = Date.now();
    let arr = hits.get(ip) || [];
    arr = arr.filter(t => now - t < WINDOW_MS);
    arr.push(now);
    hits.set(ip, arr);
    return arr.length > MAX_HITS;
}
setInterval(() => {
    const now = Date.now();
    for (const [ip, arr] of hits) {
        const fresh = arr.filter(t => now - t < WINDOW_MS);
        if (!fresh.length) hits.delete(ip);
        else hits.set(ip, fresh);
    }
}, 30_000).unref?.();

// --- Canonical odds (MUST mirror js/casino.js) -------------------------------
const FISHBET_ODDS = {
    common:    { mult: 1.2, ch: 35 },
    rare:      { mult: 1.6, ch: 28 },
    epic:      { mult: 2.5, ch: 20 },
    legendary: { mult: 5,   ch: 10 },
    mythic:    { mult: 12,  ch: 5  },
};
// weights mirror Casino.slotSymbols order (9 symbols)
const SLOT_WEIGHTS = [30, 25, 15, 10, 8, 5, 3, 2, 1];

function randInt(n) { return crypto.randomInt(n); }

function rollRoulette() { return randInt(38); } // 0..36, 37 = '00'

function weightedSlotIndex() {
    const total = SLOT_WEIGHTS.reduce((a, b) => a + b, 0);
    let r = randInt(total);
    for (let i = 0; i < SLOT_WEIGHTS.length; i++) {
        r -= SLOT_WEIGHTS[i];
        if (r < 0) return i;
    }
    return SLOT_WEIGHTS.length - 1;
}

function rollSlots() { return [weightedSlotIndex(), weightedSlotIndex(), weightedSlotIndex()]; }

function rollFishbet(rarity) {
    const odds = FISHBET_ODDS[rarity] || { mult: 1, ch: 5 };
    const roll = Math.random() * 100; // uniformity is fine; secrecy comes from server
    // Use crypto for the deciding bit:
    const winRoll = randInt(10000) / 100; // 0..99.99
    return { won: winRoll < odds.ch, roll: winRoll, mult: odds.mult, ch: odds.ch };
}

const SUITS = ['\u2660', '\u2665', '\u2666', '\u2663'];
const VALUES = ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'];
function drawCard() {
    return { suit: SUITS[randInt(4)], value: VALUES[randInt(13)] };
}

function sign(obj) {
    const payload = JSON.stringify(obj);
    const sig = crypto.createHmac('sha256', SECRET).update(payload).digest('hex');
    return { payload: obj, sig };
}

function verify(payload, sig) {
    try {
        const expect = crypto.createHmac('sha256', SECRET).update(JSON.stringify(payload)).digest('hex');
        return crypto.timingSafeEqual(Buffer.from(expect), Buffer.from(String(sig)));
    } catch { return false; }
}

function clampBet(bet) {
    bet = Math.floor(Number(bet));
    if (!Number.isFinite(bet)) return null;
    if (bet < 1 || bet > 1000) return null;
    return bet;
}

function readJson(req, maxBytes) {
    maxBytes = maxBytes || 8192;
    return new Promise((resolve) => {
        let body = '';
        req.on('data', (c) => { body += c; if (body.length > maxBytes) { try { req.destroy(); } catch {} resolve(null); } });
        req.on('end', () => {
            try { resolve(JSON.parse(body || '{}')); }
            catch { resolve(null); }
        });
        req.on('error', () => resolve(null));
    });
}

function json(res, code, obj) {
    const data = Buffer.from(JSON.stringify(obj));
    res.writeHead(code, {
        'Content-Type': 'application/json; charset=utf-8',
        'Content-Length': data.length,
        'Cache-Control': 'no-store',
    });
    res.end(data);
}

/**
 * Try to handle an /api/* request. Returns true if handled.
 */
async function handleApi(req, res, clientIp) {
    const path = req.url.split('?')[0];
    if (path === '/api/health') {
        if (req.method !== 'GET') { json(res, 405, { ok: false }); return true; }
        json(res, 200, { ok: true, authoritative: true, time: Date.now() });
        return true;
    }
    if (path === '/api/casino/bet') {
        if (req.method !== 'POST') { json(res, 405, { ok: false, message: 'POST only' }); return true; }
        if (rateLimited(clientIp)) { json(res, 429, { ok: false, message: 'Too many rolls — slow down' }); return true; }
        const body = await readJson(req);
        if (!body) { json(res, 400, { ok: false, message: 'Bad JSON' }); return true; }
        const game = String(body.game || '');
        const bet = clampBet(body.bet);
        if (!bet) { json(res, 400, { ok: false, message: 'Bet must be 1..1000' }); return true; }

        let result = null;
        if (game === 'roulette') {
            result = { game, pocket: rollRoulette() };
        } else if (game === 'slots') {
            result = { game, reels: rollSlots() };
        } else if (game === 'fishbet') {
            const rarity = String((body.extra && body.extra.rarity) || 'common').slice(0, 16);
            const r = rollFishbet(rarity);
            result = { game, rarity, won: r.won, mult: r.mult, ch: r.ch };
        } else if (game === 'highlow') {
            result = { game, card: drawCard() };
        } else {
            json(res, 400, { ok: false, message: 'Unknown game' });
            return true;
        }
        result.bet = bet;
        result.nonce = crypto.randomBytes(8).toString('hex');
        const receipt = sign(result);
        json(res, 200, { ok: true, result: receipt.payload, sig: receipt.sig });
        return true;
    }
    if (path === '/api/receipt/verify') {
        if (req.method !== 'POST') { json(res, 405, { ok: false }); return true; }
        const body = await readJson(req);
        if (!body) { json(res, 400, { ok: false }); return true; }
        json(res, 200, { ok: verify(body.payload, body.sig) });
        return true;
    }
    // --- Server-side shop quotes: client must pay catalog price ------------
    // POST { kind: 'weapon'|'rod'|'ammo'|'bucket', id, qty }
    // Returns canonical { price } so F12 price edits (price=0) are ignored.
    if (path === '/api/shop/quote') {
        if (req.method !== 'POST') { json(res, 405, { ok: false }); return true; }
        if (econLimited(clientIp)) { json(res, 429, { ok: false, message: 'Too many shop ops' }); return true; }
        const body = await readJson(req);
        if (!body) { json(res, 400, { ok: false }); return true; }
        const cat = loadCatalog();
        const kind = String(body.kind || '');
        const id = String(body.id || '').slice(0, 64);
        const qty = Math.max(1, Math.min(999, Math.floor(Number(body.qty) || 1)));
        let unit = null;
        if (kind === 'weapon' && cat.weapons[id]) unit = cat.weapons[id].price;
        else if (kind === 'rod' && cat.rods[id]) unit = cat.rods[id].price;
        else if (kind === 'bucket' && Array.isArray(cat.buckets)) {
            const b = cat.buckets.find(x => x && String(x.cap) === id);
            if (b) unit = b.price;
        } else if (kind === 'ammo' && cat.ammoPrices && cat.ammoPrices[id] !== undefined) {
            const u = cat.ammoPrices[id];
            unit = (u === null || u === Infinity) ? null : u;
            if (unit === Infinity) { json(res, 200, { ok: true, price: 0, infinite: true }); return true; }
        }
        if (unit === null || unit === undefined || !Number.isFinite(unit) || unit < 0) {
            json(res, 400, { ok: false, message: 'Unknown item' });
            return true;
        }
        const total = unit * qty;
        const receipt = sign({ kind, id, qty, price: total, nonce: crypto.randomBytes(8).toString('hex') });
        json(res, 200, { ok: true, price: total, unit, result: receipt.payload, sig: receipt.sig });
        return true;
    }
    // --- Server-side sell clamp: rejects impossible fish values ------------
    // POST { items: [{ id, value }] } -> { approvedTotal, rejected }
    if (path === '/api/shop/sell') {
        if (req.method !== 'POST') { json(res, 405, { ok: false }); return true; }
        if (econLimited(clientIp)) { json(res, 429, { ok: false, message: 'Too many shop ops' }); return true; }
        const body = await readJson(req, 65536);
        if (!body || !Array.isArray(body.items)) { json(res, 400, { ok: false }); return true; }
        const cat = loadCatalog();
        if (body.items.length > 200) { json(res, 400, { ok: false, message: 'Too many items' }); return true; }
        let approved = 0, rejected = 0;
        for (const it of body.items) {
            const id = String((it && it.id) || '').slice(0, 64);
            const v = Math.floor(Number((it && it.value) || 0));
            const base = cat.fishValues[id];
            // Unknown ids (summon keys/trophies) get a generous cap instead of
            // a hard reject so content updates don't brick selling.
            const cap = (base !== undefined ? Math.ceil(base * 4 * (cat.fishValueMult || 1)) + 1000 : (cat.maxSellPerFish || 100000));
            if (!Number.isFinite(v) || v <= 0 || v > cap) { rejected++; continue; }
            approved += v;
        }
        // Per-request cap: nobody legitimately sells >500 fish at once.
        approved = Math.min(approved, 50_000_000);
        const receipt = sign({ approved, rejected, n: body.items.length, nonce: crypto.randomBytes(8).toString('hex') });
        json(res, 200, { ok: true, approvedTotal: approved, rejected, result: receipt.payload, sig: receipt.sig });
        return true;
    }
    // --- Save signing: tamper-evident receipts for localStorage saves -----
    if (path === '/api/save/sign') {
        if (req.method !== 'POST') { json(res, 405, { ok: false }); return true; }
        const body = await readJson(req, 262144);
        if (!body || typeof body.save !== 'object') { json(res, 400, { ok: false }); return true; }
        const receipt = sign({ save: body.save, at: Date.now() });
        json(res, 200, { ok: true, result: receipt.payload, sig: receipt.sig });
        return true;
    }
    if (path === '/api/save/verify') {
        if (req.method !== 'POST') { json(res, 405, { ok: false }); return true; }
        const body = await readJson(req, 262144);
        if (!body) { json(res, 400, { ok: false }); return true; }
        json(res, 200, { ok: verify(body.payload, body.sig) });
        return true;
    }
    if (path.startsWith('/api/')) { json(res, 404, { ok: false, message: 'Unknown API' }); return true; }
    return false;
}

module.exports = { handleApi, verify, sign, SECRET: '[redacted]' };
